/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import {
  DatePickerItem,
  DatePickerState,
  Inputs,
  OptionsState,
  RangePickerState,
} from './models/datepicker.interface';

import {
  DateItemList as DateItemList
} from './components/calendar-date-item/calendar-date-item';

declare global {
  interface HTMLDateItemListElement extends DateItemList, HTMLStencilElement {
  }
  var HTMLDateItemListElement: {
    prototype: HTMLDateItemListElement;
    new (): HTMLDateItemListElement;
  };
  interface HTMLElementTagNameMap {
    "date-item-list": HTMLDateItemListElement;
  }
  interface ElementTagNameMap {
    "date-item-list": HTMLDateItemListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "date-item-list": JSXElements.DateItemListAttributes;
    }
  }
  namespace JSXElements {
    export interface DateItemListAttributes extends HTMLAttributes {
      dataItemConfig?: {
    animation: string,
    itemList: DatePickerItem[]
  };
      dateItemList?: DatePickerItem[];
    }
  }
}


import {
  DatepickerInput as DatepickerInput
} from './components/datepicker-input/datepicker-input';

declare global {
  interface HTMLDatepickerInputElement extends DatepickerInput, HTMLStencilElement {
  }
  var HTMLDatepickerInputElement: {
    prototype: HTMLDatepickerInputElement;
    new (): HTMLDatepickerInputElement;
  };
  interface HTMLElementTagNameMap {
    "datepicker-input": HTMLDatepickerInputElement;
  }
  interface ElementTagNameMap {
    "datepicker-input": HTMLDatepickerInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "datepicker-input": JSXElements.DatepickerInputAttributes;
    }
  }
  namespace JSXElements {
    export interface DatepickerInputAttributes extends HTMLAttributes {
      datepickerModel?: DatePickerState;
      optionsModel?: OptionsState;
    }
  }
}


import {
  DatepickerModal as DatepickerModal
} from './components/datepicker-modal/datepicker-modal';

declare global {
  interface HTMLDatepickerModalElement extends DatepickerModal, HTMLStencilElement {
  }
  var HTMLDatepickerModalElement: {
    prototype: HTMLDatepickerModalElement;
    new (): HTMLDatepickerModalElement;
  };
  interface HTMLElementTagNameMap {
    "datepicker-modal": HTMLDatepickerModalElement;
  }
  interface ElementTagNameMap {
    "datepicker-modal": HTMLDatepickerModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "datepicker-modal": JSXElements.DatepickerModalAttributes;
    }
  }
  namespace JSXElements {
    export interface DatepickerModalAttributes extends HTMLAttributes {
      datepickerModel?: DatePickerState;
      optionsModel?: OptionsState;
    }
  }
}


import {
  RangepickerInput as RangepickerInput
} from './components/rangepicker-input/rangepicker-input';

declare global {
  interface HTMLRangepickerInputElement extends RangepickerInput, HTMLStencilElement {
  }
  var HTMLRangepickerInputElement: {
    prototype: HTMLRangepickerInputElement;
    new (): HTMLRangepickerInputElement;
  };
  interface HTMLElementTagNameMap {
    "rangepicker-input": HTMLRangepickerInputElement;
  }
  interface ElementTagNameMap {
    "rangepicker-input": HTMLRangepickerInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rangepicker-input": JSXElements.RangepickerInputAttributes;
    }
  }
  namespace JSXElements {
    export interface RangepickerInputAttributes extends HTMLAttributes {
      optionsModel?: OptionsState;
      rangepickerModel?: RangePickerState;
    }
  }
}


import {
  RangepickerModal as RangepickerModal
} from './components/rangepicker-modal/rangepicker-modal';

declare global {
  interface HTMLRangepickerModalElement extends RangepickerModal, HTMLStencilElement {
  }
  var HTMLRangepickerModalElement: {
    prototype: HTMLRangepickerModalElement;
    new (): HTMLRangepickerModalElement;
  };
  interface HTMLElementTagNameMap {
    "rangepicker-modal": HTMLRangepickerModalElement;
  }
  interface ElementTagNameMap {
    "rangepicker-modal": HTMLRangepickerModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rangepicker-modal": JSXElements.RangepickerModalAttributes;
    }
  }
  namespace JSXElements {
    export interface RangepickerModalAttributes extends HTMLAttributes {
      optionsModel?: OptionsState;
      rangepickerModel?: RangePickerState;
    }
  }
}


import {
  StDatepicker as StDatepicker
} from './components/st-datepicker/st-datepicker';

declare global {
  interface HTMLStDatepickerElement extends StDatepicker, HTMLStencilElement {
  }
  var HTMLStDatepickerElement: {
    prototype: HTMLStDatepickerElement;
    new (): HTMLStDatepickerElement;
  };
  interface HTMLElementTagNameMap {
    "st-datepicker": HTMLStDatepickerElement;
  }
  interface ElementTagNameMap {
    "st-datepicker": HTMLStDatepickerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "st-datepicker": JSXElements.StDatepickerAttributes;
    }
  }
  namespace JSXElements {
    export interface StDatepickerAttributes extends HTMLAttributes {
      config?: Inputs;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
